language: node_js
node_js:
  - "0.8"
before_install:
  - npm install -g phantomjs
  - npm install -g casperjs
  - cd ./scripts
before_script:
  - phantomjs --version
  - casperjs --version
script:
  - casperjs test casperjs-test.js
